# Generated by Django 5.2 on 2025-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
