services:
  - type: web
    name: student-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn studentstudyportal.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
